name: E2E avec MySQL + Apache + Cypress

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: taskdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -prootpw"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP CLI (Composer & outils)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, sodium, zip
          coverage: none

      - name: Installer dépendances Composer
        run: composer install --no-interaction --prefer-dist

      - name: Importer la base de données
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -prootpw < base.sql

      - name: Build env.php for the app
        run: |
          cat > env.php <<'PHP'
          <?php
          const BDD_LOGIN = "root";
          const BDD_PASSWORD = "rootpw";
          const BDD_SERVER = "127.0.0.1:3306";
          const BDD_NAME = "taskdb";
          const BASE_URL = "/";
          PHP

      - name: Vérifier env.php généré
        run: |
          echo "📂 Répertoire courant:" && ls -la
          echo "📝 env.php (pass masqué):"
          sed -E 's/(BDD_PASSWORD[[:space:]]*=\s*")[^"]+/\1*** /' env.php || true
          php -r 'require "env.php"; echo "Chargé OK\n";'

      - name: Installer & configurer Apache (mod_php)
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y apache2 libapache2-mod-php
          echo "Listen 8000" | sudo tee -a /etc/apache2/ports.conf

          WORKDIR="$(pwd)"
          echo "WORKDIR=${WORKDIR}"

          sudo chmod o+x /home || true
          sudo chmod o+x /home/runner || true
          sudo chmod o+x /home/runner/work || true
          OWNER_DIR="$(dirname "$(dirname "${WORKDIR}")")"
          REPO_DIR="$(dirname "${WORKDIR}")"
          sudo chmod o+x "${OWNER_DIR}" || true
          sudo chmod o+x "${REPO_DIR}" || true
          sudo chmod -R a+rX "${WORKDIR}"

          test -f "${WORKDIR}/index.php" || (echo "❌ index.php introuvable à ${WORKDIR}" && exit 1)

          cat <<EOF | sudo tee /etc/apache2/sites-available/ci.conf
          <VirtualHost *:8000>
              ServerName localhost
              DocumentRoot ${WORKDIR}
              DirectoryIndex index.php index.html
              <Directory ${WORKDIR}>
                  AllowOverride All
                  Options Indexes FollowSymLinks
                  Require all granted
              </Directory>
              ErrorLog \${APACHE_LOG_DIR}/ci_error.log
              CustomLog \${APACHE_LOG_DIR}/ci_access.log combined
          </VirtualHost>
          EOF

          sudo a2enmod rewrite
          sudo a2dissite 000-default.conf || true
          sudo a2ensite ci.conf
          sudo systemctl restart apache2

          if ! curl -sSf http://127.0.0.1:8000/ >/dev/null; then
            echo "⚠️ Health-check KO. Logs Apache :"
            sudo tail -n 200 /var/log/apache2/ci_error.log || true
            sudo tail -n 200 /var/log/apache2/error.log || true
            exit 1
          fi

      - name: Tests Cypress
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://127.0.0.1:8000'
          config: baseUrl=http://127.0.0.1:8000
          browser: chrome
