name: Setup MySQL and load schema

on:
  push:
    paths:
      - "base.sql"
      - ".github/workflows/cypress.yml"
  workflow_dispatch:

jobs:
  db:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: taskdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -prootpw"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MySQL client & composer
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client php-cli php-mbstring unzip
          EXPECTED_CHECKSUM="$(php -r 'copy(\"https://composer.github.io/installer.sig\", \"php://stdout\");')"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') !== '$EXPECTED_CHECKSUM') { echo 'Bad installer'; unlink('composer-setup.php'); exit(1); }"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm composer-setup.php

      - name: Wait for MySQL
        run: |
          for i in {1..60}; do
            mysqladmin ping -h 127.0.0.1 -prootpw && break
            sleep 2
          done

      - name: Create database (idempotent)
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -prootpw -e \
            "CREATE DATABASE IF NOT EXISTS taskdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

      - name: Load schema from base.sql
        run: |
          # Si base.sql contient CREATE DATABASE/USE, tu peux enlever 'taskdb' ci-dessous
          mysql -h 127.0.0.1 -P 3306 -u root -prootpw taskdb < base.sql

      - name: Build env.php for the app
        run: |
          cat > env.php <<'PHP'
          <?php
          const BDD_LOGIN = "root";
          const BDD_PASSWORD = "rootpw";
          const BDD_SERVER = "127.0.0.1";
          const BDD_NAME = "taskdb";
          const BASE_URL = "/";
          PHP

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress

            
      # installation des dépendances PHP
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist
      
      # migration de la base de données
      - name: migration DB
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -prootpw < base.sql
      
      # démarrage du serveur PHP
      - name: Run PHP local server
        run: |
          php -S 127.0.0.1:8000 -t public &
      
      # Cypress Actions
      - name : Test Cypress
        uses: cypress-io/github-action@v6