name: E2E avec PHP MySQL + Apache + Cypress

on:
  push:
    branches: [main, test, refacto]
  pull_request:
    branches: [main, test, refacto]
    paths:
      - "base.sql"
      - ".github/workflows/cypress.yml"
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: taskdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -prootpw"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP CLI (Composer & outils)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Installer dépendances Composer
        run: composer install --no-interaction --prefer-dist

      - name: Migration DB
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -prootpw < base.sql

      # --- Build fichier env.php ---
      - name: Build env.php for the app
        run: |
          cat > env.php <<'PHP'
          <?php
          const BDD_LOGIN = "root";
          const BDD_PASSWORD = "rootpw";
          const BDD_SERVER = "127.0.0.1:3306";
          const BDD_NAME = "taskdb";
          const BASE_URL = "/";
          PHP

      # --- Debug: vérifier la présence et le contenu (password masqué) ---
      - name: Vérifier env.php généré
        run: |
          echo "📂 Contenu du répertoire courant :"
          ls -la
          echo
          echo "📝 env.php (mot de passe masqué) :"
          sed -E 's/(BDD_PASSWORD[[:space:]]*=\s*")[^"]+/\1*** /' env.php || true
          echo
          echo "✅ Test rapide de chargement par PHP :"
          php -r 'require "env.php"; echo "Chargé OK\n";'

      # --- Apache sert index.php à la racine ---
      - name: Installer & configurer Apache (mod_php)
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 libapache2-mod-php
          echo "Listen 8000" | sudo tee -a /etc/apache2/ports.conf
          cat <<'EOF' | sudo tee /etc/apache2/sites-available/ci.conf
          <VirtualHost *:8000>
              ServerName localhost
              DocumentRoot ${GITHUB_WORKSPACE}
              DirectoryIndex index.php index.html
              <Directory ${GITHUB_WORKSPACE}>
                  AllowOverride All
                  Options Indexes FollowSymLinks
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/ci_error.log
              CustomLog ${APACHE_LOG_DIR}/ci_access.log combined
          </VirtualHost>
          EOF
          sudo a2enmod rewrite
          sudo a2dissite 000-default.conf || true
          sudo a2ensite ci.conf
          sudo systemctl restart apache2
          curl -sSf http://127.0.0.1:8000/ >/dev/null

      - name: Tests Cypress
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://127.0.0.1:8000'
          config: baseUrl=http://127.0.0.1:8000
          browser: chrome
